
name:                elabzoo-poly-instantiation
version:             0.1.0.0
github:              "AndrasKovacs/elaboration-zoo"
license:             BSD3
author:              "Andr치s Kov치cs"
maintainer:          "puttamalac@gmail.com"
copyright:           "2019 Andr치s Kov치cs"
category:            Language

description:         "Small implementations of elaborators for type theories, with varying complexity and feature set"

default-extensions:
- BangPatterns
- ConstraintKinds
- EmptyCase
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- LambdaCase
- MultiParamTypeClasses
- NoMonomorphismRestriction
- OverloadedStrings
- PatternSynonyms
- PartialTypeSignatures
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- Strict
- TemplateHaskell
- TupleSections
- ViewPatterns

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches
- -Wno-partial-type-signatures

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- microlens-platform
- mmorph
- mtl

source-dirs: .

executable:
  main: Main.hs
