
name:                elabzoo-implicit-args
version:             0.1.0.0
github:              "AndrasKovacs/elaboration-zoo"
license:             BSD3
author:              "Andr치s Kov치cs"
maintainer:          "puttamalac@gmail.com"
copyright:           "2019 Andr치s Kov치cs"
category:            Language

description:         "Small implementations of elaborators for type theories, with varying complexity and feature set"

default-extensions:
- EmptyCase
- LambdaCase
- NoMonomorphismRestriction
- OverloadedStrings
- PatternSynonyms
- RecordWildCards
- StandaloneDeriving
- Strict
- TupleSections
- ViewPatterns
- BangPatterns
- ScopedTypeVariables

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- megaparsec
- mmorph

source-dirs: .

executable:
  main: Main.hs
