
name:                minimal-tt-examples
version:             0.1.0.0
github:              "AndrasKovacs/minimal-tt-examples"
license:             BSD3
author:              "Andr치s Kov치cs"
maintainer:          "puttamalac@gmail.com"
copyright:           "2018 Andr치s Kov치cs"
category:            Language

description:         "Minimal implementations for features in dependent type checking and elaboration"

dependencies:
- base >= 4.7 && < 5
- containers
- mtl

library:
  source-dirs: .
