
name:                tcbe
version:             0.1.0.0
github:              "AndrasKovacs/tcbe"
license:             BSD3
author:              "Andr치s Kov치cs"
maintainer:          "puttamalac@gmail.com"
copyright:           "2018 Andr치s Kov치cs"
category:            Language

description:         "Notes on dependent type checking & inference"

dependencies:
- base >= 4.7 && < 5
- containers
- mtl

library:
  source-dirs: .
