
resolver: lts-16.19

packages:
  - 01-eval-closures-debruijn/
  - 01-eval-closures-names/
  - 01-eval-HOAS-names/
  - 02-typecheck-closures-debruijn/
  - 02-typecheck-HOAS-names/
  - 03-holes/
  - 04-implicit-args/
