
resolver: lts-15.8

packages:
  - 01-eval-closures-debruijn/
  - 01-eval-closures-names/
  - 01-eval-HOAS-names/
  - 02-typecheck-closures-debruijn/
  - 02-typecheck-HOAS-names/
  - 03-holes/
  - 03-holes-debruijn/
  - 04-implicit-args/
