
name:                elabzoo-eval-closures-debruijn
version:             0.1.0.0
github:              "AndrasKovacs/elaboration-zoo"
license:             BSD3
author:              "Andr치s Kov치cs"
maintainer:          "puttamalac@gmail.com"
copyright:           "2019 Andr치s Kov치cs"
category:            Language

description:         "Small implementations of elaborators for type theories, with varying complexity and feature set"

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches

dependencies:
- base >= 4.7 && < 5
- megaparsec

source-dirs: .

executable:
  main: Main.hs
