
name:                elabzoo-holes-unit-eta
version:             0.1.0.0
github:              "AndrasKovacs/elaboration-zoo"
license:             BSD3
author:              "Andr치s Kov치cs"
maintainer:          "puttamalac@gmail.com"
copyright:           "2024 Andr치s Kov치cs"
category:            Language

description:         "Small implementations of elaborators for type theories, with varying complexity and feature set"

default-extensions:
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DerivingVia
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- PatternSynonyms
- ScopedTypeVariables
- StandaloneDeriving
- Strict
- TupleSections
- ViewPatterns

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches
- -Wno-missing-pattern-synonym-signatures

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec

source-dirs: .

executable:
  main: Main.hs
