name: check-typos

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:

  check-typos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: typos-action
        uses: crate-ci/typos@v1.31.1
